### ISSUE TITLE
what happens when player drops mid-game

### ISSUE THREAD

**Issue by ghost** [hewhowearspants/Cards-Against-Your-Sanity#24]
if cardCzar, reset game
if player and if player played cards, remove played cards
if playercount below minimum, kick back to lobby(after implementing minimums)

keep testing players joining/leaving at various stages of the game

~~player leaves mid player selection~~
player leaves between rounds (before everyone hits ok)
- player left before not hitting ok
- player leave after hitting ok

card czar leaves before all cards submitted
card czar leavers during card selection

**Comment by hewhowearspants** [comment]
instead of automatically booting to lobby, possibly display a model saying "waiting for more players", give option to leave game, automatically resume game when minimum # of players join. Maybe?

**Comment by hewhowearspants** [comment]
when player leaves between rounds (waiting for everyone to click OK), game does not continue, but the server doesn't crash either

**Comment by hewhowearspants** [comment]
when card czar leaves while waiting for players to submit cards, next player becomes czar, but does not get a START button, and other players don't reset.

(Interestingly enough, if the number of players drops below 3 after that, and someone else joins to continue the game, the game is properly reset and can continue as normal)

**Comment by hewhowearspants** [comment]
when player count goes below 3 and a pending player is added, a new card czar is chosen, but previous card czar does not get told about this and thus does not revert to a player
